# Ensure that python is available
- name: "Deploy {{ environment_id }} App"
  become: yes
  hosts: "{{ environment_id }}-academy"
  vars_files:
    - "infra/{{ environment_id }}.yml"
    - "config/{{ environment_id }}.yml"
    - "secrets/{{ environment_id }}.yml"
  tasks:
    - name: "Start Drupal container"
      docker_container:
        restart_policy: unless-stopped
        state: started
        pull: yes
        name: "drupal"
        image: "{{ project.images.academy }}"
        ports:
          - 8080:80
        env:
          TZ: "Europe/Helsinki"
          MYSQL_HOST: "{{ infra.private_ip.academy }}"
          MYSQL_PORT: "3306"
          MYSQL_USERNAME: "{{ secrets.academy.mysql.username }}"
          MYSQL_PASSWORD: "{{ secrets.academy.mysql.password }}"
          MYSQL_DATABASE: "{{ secrets.academy.mysql.database }}"
          THEME_DEBUG: "0"
          SITE_HASH_SALT: "{{ secrets.academy.drupal.hash_salt }}"
          BASE_URL: "{{ project.drupal.base_url }}"
          REDIS_CACHE: "0"
          REVERSE_PROXY_ENABLED: "1"
          STRIPE_SECRET_KEY: "{{ secrets.stripe.secret_key }}"
          STRIPE_PUBLIC_KEY: "{{ secrets.stripe.public_key }}"
          STRIPE_WEBHOOK_SECRET: "{{ secrets.stripe.webhook_secret }}"
          REGISTRATION_ADMIN_EMAIL: "academy@colosseumdental.com"
        volumes:
          - "site-files:/var/www/web/sites/default/files"
  roles:
    - job-login-thp-docker-registry
